### ISSUE TITLE
KnownUserException: integrationsConfigString can not be null or empty

### ISSUE THREAD

**Issue by kenorb** [queueit/KnownUser.V3.PHP#12]
Our site is failing on fatal error, because the library fails accessing the integration config URL at http://CLIENT.queue-it.net/status/integrationconfig/CLIENT

> Request failed! HTTP/1.1 403 Forbidden in QueueitKnownUser->getIntegrationConfig() (line 202 of QueueitKnownUser.php).

> 22/Nov 12:23  error  queueit  QueueIT\KnownUserV3\SDK\KnownUserException: integrationsConfigString can not be null or empty. in QueueIT\KnownUserV3\SDK\KnownUser::validateRequestByIntegrationConfig() (line 140 of sites/all/libraries/composer/queueit/knownuserv3/KnownUser.php).

The above error is not catchable via `try` and `catch` block so it breaks the whole site.

**Comment by queueit** [comment]
Hi kenorb,
Can you tell me which IP your server(s) have? I will check if they have been blocked by firewall.

**Comment by queueit** [comment]
The sample provided in the README has a try catch block. Please reach out to our support team if you need any assistance.

**Comment by kenorb** [comment]
Our implementation of the library also got `try`/`catch`  as per [queueit.module](https://github.com/National-Theatre/queueit/blob/0cf0843801a3ea92b9470a7739ac03ef9a613acf/queueit.module#L66), but it seems it didn't catch the error.
I'll try to expand the block and see if that helps.

**Comment by queueit** [comment]
From what I can see the underlying problem is that our servers are being called (to get integration config) every time a request comes in. This is happening in the queueit drupal module, and should be fixed there. We recommend to store/cache this somewhere (https://github.com/queueit/KnownUser.V3.PHP/tree/master/Documentation)
I found similar concern here: https://github.com/drupal-modules/queueit/issues/2
