### ISSUE TITLE
Undefined offset: 1 in QueueITHelpers.php

### ISSUE THREAD

**Issue by gemal** [queueit/KnownUser.V3.PHP#14]
I saw the following error this morning.

```
Undefined offset: 1 in [Vendor/queueit/knownuserv3/QueueITHelpers.php, line 38]
IP:173.252.127.38
UA:facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)
URL:/event?queueittoken=e_dinnerdays201942~q_59a11232-313c-4e3c-9260-f7e80a0ffd25~ts
Method:HEAD
```

we use latest version:
```
"name": "queueit/knownuserv3",
"version": "3.5.2",
```

**Comment by frwiqueueit** [comment]
Thank you @gemal ,
We will look into it.

**Comment by frwiqueueit** [comment]
Hi again, just wanted to be sure the URL in the example is correct:
event?queueittoken=e_dinnerdays201942~q_59a11232-313c-4e3c-9260-f7e80a0ffd25~ts
I can see it only contains "half" of the queueittoken. Was it submitted this way? Then it makes sense the code breaks because timestamp key (ts) is there but no value.
Do you know why you receive request with only a partial queueittoken?

**Comment by gemal** [comment]
the useragent was UA:facebookexternalhit/1.1 so a bot from Facebook.
Perhaps someone pasted a URL or something.
Perhaps the library could just return early if you hit this case.

**Comment by frwiqueueit** [comment]
Makes sense, thank you. We will submit a code update ASAP.
